name: Release

on:
  release:
    types: [published]
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Compile the project
      run: bun run compile

    - name: Update release
      uses: softprops/action-gh-release@v2
      with:
        files: ./builds/**